# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

controller:
  image:
    registry: ""
    repository: atomix/controller
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/controller-init-certs
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []

runtime:
  version: v0.0.0
  image:
    registry: ""
    repository: atomix/runtime
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []
