# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

controller:
  image:
    registry: ""
    repository: atomix/kubernetes-controller
    tag: v0.1.0
    pullPolicy: IfNotPresent
    pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/kubernetes-controller-init-certs
    tag: v0.1.0
    pullPolicy: IfNotPresent
    pullSecrets: []
