# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the application. The application spec contains binding rules that are used to
                map primitives to clusters.
              type: object
              properties:
                bindings:
                  type: array
                  items:
                    type: object
                    required:
                      - cluster
                    properties:
                      cluster:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      rules:
                        type: array
                        items:
                          type: object
                          properties:
                            kinds:
                              type: array
                              items:
                                type: string
                            names:
                              type: array
                              items:
                                type: string
                            metadata:
                              type: object
                              additionalProperties:
                                type: string
            status:
              type: object
              properties: { }
      additionalPrinterColumns: [ ]