# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bindings.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: Binding
    listKind: BindingList
    plural: bindings
    singular: binding
  versions:
    - name: v3beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the binding. Contains rules that are used to map primitives to clusters.
              type: object
              properties:
                required:
                  - cluster
                properties:
                  cluster:
                    type: object
                    required:
                      - name
                    properties:
                      namespace:
                        type: string
                      name:
                        type: string
                  rules:
                    type: array
                    items:
                      type: object
                      properties:
                        kinds:
                          type: array
                          items:
                            type: string
                        names:
                          type: array
                          items:
                            type: string
                        metadata:
                          type: object
                          additionalProperties:
                            type: string