# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the cluster. The spec must include a protocol configuration describing how the
                cluster should be implemented.
              type: object
              properties:
                driver:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties: { }
      additionalPrinterColumns: [ ]