# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fusionengines.atomix.io
spec:
  group: atomix.io
  scope: Cluster
  names:
    kind: Driver
    listKind: DriverList
    plural: drivers
    singular: driver
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - repo
          properties:
            repo:
              type: object
              properties:
                url:
                  type: string