# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: profiles.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: Profile
    listKind: ProfileList
    plural: profiles
    singular: profile
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - spec
              properties:
                spec:
                  type: object
                  required:
                    - bindings
                  properties:
                    bindings:
                      type: array
                      items:
                        type: object
                        required:
                          - store
                          - primitives
                        properties:
                          store:
                            type: object
                            required:
                              - name
                            properties:
                              namespace:
                                type: string
                              name:
                                type: string
                          primitives:
                            type: array
                            items:
                              type: object
                              required:
                                - kinds
                                - apiVersions
                              properties:
                                kinds:
                                  type: array
                                  items:
                                    type: string
                                apiVersions:
                                  type: array
                                  items:
                                    type: string
                                names:
                                  type: array
                                  items:
                                    type: string
                                tags:
                                  type: object
                                  additionalProperties:
                                    type: string
      additionalPrinterColumns: [ ]