# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: protocols.atomix.io
spec:
  group: atomix.io
  scope: Cluster
  names:
    kind: Protocol
    listKind: ProtocolList
    plural: protocols
    singular: protocol
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - versions
          properties:
            versions:
              description: |-
                A list of protocol versions and available drivers for each version.
              type: array
              items:
                type: object
                required:
                  - name
                  - drivers
                properties:
                  name:
                    type: string
                  drivers:
                    type: array
                    items:
                      type: object
                      required:
                        - runtimeVersion
                        - image
                        - path
                      properties:
                        runtimeVersion:
                          type: string
                        image:
                          type: string
                        path:
                          type: string
