# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stores.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: Store
    listKind: StoreList
    plural: stores
    singular: store
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              required:
                - driver
              properties:
                driver:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
